services:
  flask:
    image: flask-v2
    ports:
      - "5000:5000"
    build: .
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
volumes:
  mongodbdata:
  appdata: